{% set version = "2.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsvg
  version: {{ version|replace("-", "_") }}

source:
  fn: rsvg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsvg/rsvg_{{ version }}.tar.gz
  sha256: 72e27ee5d26ee2d3e086eeef8fdc71ecb83487b8d39f27492b86b9fd4223dc24

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spelling, svglite, png, jpeg, webp, ggplot2
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - librsvg              # [not win]
    - glib                 # [not win]

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - librsvg              # [not win]

test:
  commands:
    - $R -e "library('rsvg')"  # [not win]
    - "\"%R%\" -e \"library('rsvg')\""  # [win]

about:
  home: https://github.com/jeroen/rsvg#readme
  license: MIT
  summary: Renders vector-based svg images into high-quality custom-size bitmap arrays using 'librsvg2'. The resulting bitmap can be written to e.g. png, jpeg or webp format. In addition, the package can convert images directly to various formats such as pdf or postscript.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
