{% set version = '1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsvg
  version: {{ version|replace("-", "_") }}

source:
  fn: rsvg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsvg/rsvg_{{ version }}.tar.gz
  sha256: efa47a79d09077f3c771ad2be3492259783cba262130cc0b79533b68dc63ac86

build:
  merge_build_host: True  # [win]
  number: 3
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - librsvg              # [not win]

  run:
    - r-base
    - librsvg  # [not win]

test:
  commands:
    - $R -e "library('rsvg')"  # [not win]
    - "\"%R%\" -e \"library('rsvg')\""  # [win]

about:
  home: https://github.com/jeroen/rsvg#readme
  license: MIT
  summary: Renders vector-based svg images into high-quality custom-size bitmap arrays using
    'librsvg2'. The resulting bitmap can be written to e.g. png, jpeg or webp format.
    In addition, the package can convert images directly to various formats such as
    pdf or postscript.
  license_family: MIT

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - jenzopr
