{% set version = "2.6.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsvg
  version: {{ version|replace("-", "_") }}

source:
  fn: rsvg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsvg/rsvg_{{ version }}.tar.gz
  sha256: 7e6ab0685c37fa2074f44fddcca407989c8bc15fdee2f319c317662b4d48c955

build:
  number: 0
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - librsvg                      # [not win]
    - glib                         # [not win]
    - cairo                        # [not win]
  run:
    - r-base
    - librsvg                      # [not win]
    - cairo                        # [not win]

test:
  commands:
    - $R -e "library('rsvg')"  # [not win]
    - "\"%R%\" -e \"library('rsvg')\""  # [win]

about:
  home: https://github.com/jeroen/rsvg
  doc_url: https://docs.ropensci.org/rsvg/
  license: MIT
  summary: Renders vector-based svg images into high-quality custom-size bitmap arrays using 'librsvg2'. The resulting bitmap can be written to e.g. png, jpeg or webp format. In addition, the package can convert images directly to various formats such as pdf or postscript.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
