travis:
  secure:
    BINSTAR_TOKEN: Ctb7qtv217EmWOfayweeOMhE2IQDY1ci8BXr2PqSq2hxjj/15TJOd6kZ7qhSD/dmK2vl4ZXEPw8mj9sxBqgbPJg5WCvIwMfHxZD+h7BSSo1uL96rGqo7ItBinnNW9Gsqy7W/hd5Ly9YP7YoNmdCWx243Q2kTf75QUyBWqotAuQaKzgq/TJ9YLOwUaWEhJaXI4l+SuK2FYyv2mf24bOp6A8K0Zsg8aRW5TUOdNAVXYeO1e2n7HXhL8/yb5g67h4G2iufS4658FTZ0Xd/iRJr7YNLUpmvBz3Th5hCNxAXMIKmpbo17oU4dRuNQsdKOC/hnZ7v9dwhmu98j5ArFUVsOUi0A3AMR2Foo7ktDWDwyy2czIDw1wpVvysOljaPuvveYcshAu+JfdT36fLjUGBZ+4j7NvRU7bbfflY+Iq9CMVcfezdjN8czwq/V5U0UthNAcmuuw36oxndMDj2sQyn6ODYf4EqYF7l3S39Z6+faDXQ6qaXdy6Ih29bIh1QUanP9LUeiyk30qR8xsPXlrbKKNATWq23D4OVewozsXNWXnUgvQt6Y7Cea+UUnlOl7yeRIpP7IpD5d6uuVPAbTk6j7uJgZQJ/muKgeHUv7gXWLLijty21X2HY+aWcKJSHZnBQHc2ND2+nZCxt0U/5dZXO+NFIQxxKFYa9kDrOeeEmrdjHA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
